name: Robot Framework

on:
  push:
    branches: [ main ]

jobs:
    start_run:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          uses: joonvena/robotframework-docker-action@v1.0
          with:
            browser: chromium
            robot_tests_dir: /testcase
            robot_reports_dir: /report
        - name: Upload test results
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: report
            path: report

    generate_report:
        if: always()
        needs: [start_run] 
        runs-on: ubuntu-latest
        steps:
        - name: Download reports
          uses: actions/download-artifact@v3
          with:
            name: report

        - name: Get Repository Owner & Name
          run: |
            export OWNER="$(echo "${{ github.repository }}" | awk -F / '{print $1}' | sed -e "s/:refs//")"
            export REPO="$(echo "${{ github.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")"
          # echo "::set-env name=REPOSITORY_OWNER::$OWNER"
          # echo "::set-env name=REPOSITORY_NAME::$REPO"

            echo "REPOSITORY_OWNER" >> $OWNER
            echo "REPOSITORY_NAME" >> $REPO

        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v2
          env:
            GH_ACCESS_TOKEN: ${{ secrets.TOKEN }}
            REPO_OWNER: ${{ env.REPOSITORY_OWNER }}
            COMMIT_SHA: ${{ github.sha }}
            REPOSITORY: ${{ env.REPOSITORY_NAME }}
            REPORT_PATH: report